/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DemoPokemonsImport } from './routes/demo.pokemons'
import { Route as DemoBooksImport } from './routes/demo.books'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoPokemonsRoute = DemoPokemonsImport.update({
  id: '/demo/pokemons',
  path: '/demo/pokemons',
  getParentRoute: () => rootRoute,
} as any)

const DemoBooksRoute = DemoBooksImport.update({
  id: '/demo/books',
  path: '/demo/books',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo/books': {
      id: '/demo/books'
      path: '/demo/books'
      fullPath: '/demo/books'
      preLoaderRoute: typeof DemoBooksImport
      parentRoute: typeof rootRoute
    }
    '/demo/pokemons': {
      id: '/demo/pokemons'
      path: '/demo/pokemons'
      fullPath: '/demo/pokemons'
      preLoaderRoute: typeof DemoPokemonsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/books': typeof DemoBooksRoute
  '/demo/pokemons': typeof DemoPokemonsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/books': typeof DemoBooksRoute
  '/demo/pokemons': typeof DemoPokemonsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo/books': typeof DemoBooksRoute
  '/demo/pokemons': typeof DemoPokemonsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/books' | '/demo/pokemons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/books' | '/demo/pokemons'
  id: '__root__' | '/' | '/demo/books' | '/demo/pokemons'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoBooksRoute: typeof DemoBooksRoute
  DemoPokemonsRoute: typeof DemoPokemonsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoBooksRoute: DemoBooksRoute,
  DemoPokemonsRoute: DemoPokemonsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo/books",
        "/demo/pokemons"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo/books": {
      "filePath": "demo.books.tsx"
    },
    "/demo/pokemons": {
      "filePath": "demo.pokemons.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
